# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be10b6ccfd6afef870c52efbf60f517e033a7b7cc87eefda3101669e9d72ae80c72a303de6dfd2077911e9eecf3bc6ced95c02268546938cf56164386105a708

test:
  secret_key_base: 87c70a8709fa27ee8a44edf6f5700bc454f4cc182a366b885a2a554f6ba64dc332169ae520797f7c8767a9a37b96af287aa821506627853f337c41436f75a15b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
